all: compile

compile:
	javac Task2.java

run:
	java -Xmx512m Task2

clean:
	rm -f *.class
	rm -f evaluators/*.class
	rm -f exceptions/*.class
	rm -f expressions/*.class
	rm -f expressions/constants/*.class
	rm -f expressions/operations/*.class
	rm -f expressions/operations/impl/*.class
	rm -f expressions/predicates/*.class
	rm -f expressions/predicates/impl/*.class
	rm -f expressions/quantifier/*.class
	rm -f expressions/quantifier/impl/*.class
	rm -f expressions/subject/*.class
	rm -f expressions/subject/impl/*.class
	rm -f expressions/util/*.class
	rm -f my/*.class
	rm -f my/proofs/*.class
	rm -f my/theory/*.class
	rm -f my/util/*.class
	rm -f parser/*.class
	rm -f parser/impl/*.class
	rm -f parser/tokenizer/*.class
	rm -f util/*.class